### ISSUE TITLE
OSX 10.14.6 and hyper didnt work

### ISSUE THREAD

**Issue by mhzawadi** [gWOLF3/moter#4] opened 2019-11-18 12:05 UTC
Have followed the install and I couldnt get it to work

```shell
99% 11:59:38 py-2.7.16 LPT00334MAC in ~/
± |1.2.12 ✓| → moter start
Traceback (most recent call last):
  File "site-packages/psutil/_psosx.py", line 362, in catch_zombie
  File "site-packages/psutil/_psosx.py", line 426, in cmdline
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "moter.py", line 150, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "moter.py", line 121, in start
  File "moter.py", line 121, in <genexpr>
  File "site-packages/psutil/__init__.py", line 610, in name
  File "site-packages/psutil/__init__.py", line 663, in cmdline
  File "site-packages/psutil/_psosx.py", line 342, in wrapper
  File "site-packages/psutil/_psosx.py", line 426, in cmdline
  File "contextlib.py", line 130, in __exit__
  File "site-packages/psutil/_psosx.py", line 373, in catch_zombie
psutil._exceptions.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=1437)
[26743] Failed to execute script moter
```

**Comment by gWOLF3** [comment] 2019-11-18 17:53
Thanks for submitting. 

I know the cause of this bug - it's an exception thrown when psutil hits a zombie process when looping through process list. I think I know the fix for this and will push a patch today to handle this exception. 

In the meantime, you can clear out any zombie process on your machine and that should fix the problem. Try the following:

1) `ps aux | grep -w Z` - find all zombie processes
2) `ps -o ppid= $PID_OF_ZOMBIE`- get the parent of zombie process
3) `kill $PID_OF_ZOMBIE_PARENT` - kill the parent of the zombie process

If you find that you have quite a few zombie processes sitting around, it may be a good idea to restart your computer, if you have not done so in a while.

**Closed as completed** 2022-11-12 22:38 UTC
